// Generated by CoffeeScript 1.9.3
(function() {
  var URI, url, urlHelper;

  url = require("url");

  URI = require("URIjs");

  urlHelper = {
    isAbsoluteUrl: function(uri) {
      return (new URI(uri)).is("absolute");
    },
    resolveRelativeUrl: function(to, from) {
      var uri;
      if (module.exports.isAbsoluteUrl(to)) {
        return to;
      }
      uri = new URI("/" + to).relativeTo("/" + from);
      if (uri.filename() === "index.html") {
        if (uri.directory() === "") {
          uri = uri.directory(".");
        }
        uri = uri.filename("");
      }
      return uri.toString();
    },
    validateAbsoluteUrl: function(remoteUrl) {
      var protocol;
      if (remoteUrl == null) {
        return false;
      }
      protocol = url.parse(remoteUrl).protocol;
      return protocol === "http:" || protocol === "https:";
    },
    normalizeUrl: function(uri, pagePath) {
      if (urlHelper.isAbsoluteUrl(uri)) {
        if (urlHelper.validateAbsoluteUrl(uri)) {
          return uri;
        }
        return null;
      }
      return urlHelper.resolveRelativeUrl(uri, pagePath);
    }
  };

  module.exports = urlHelper;

}).call(this);
